global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
          
  - job_name: prometheus  
    static_configs:
      - targets:
          - 192.168.0.194:9100 # IP Address of the Prometheus Server

  - job_name: kubernetes-cluster 
    static_configs:
      - targets:
          - 192.168.0.160:9100 # Master-1 IP Address
          - 192.168.0.161:9100 # Master-2 IP Address
          - 192.168.0.162:9100 # Worker-1 IP Address
          - 192.168.0.163:9100 # Worker-2 IP Address
          - 192.168.0.164:9100 # Worker-3 IP Address
          - 192.168.0.165:9100 # Worker-4 IP Address